title:             m-----
email:             your-email@example.com
description:       A Blog 
author:            HSng
baseurl:           ""
url:               "http://hsynguyen.github.io"

# Social Profiles
twitter_username:  
github_username:   
facebook_username: 

# Build settings
markdown:          kramdown
mathjax:           true
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
